AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Testing idempotency timeouts
Globals:
  Function:
      Timeout: 2
      Runtime: python3.9
      MemorySize: 512
      Layers: 
        - !Ref PowertoolsLayer
      Environment:
        Variables:
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: example
          DYNAMODB_TABLE: !Ref IdempotencyTable

Resources:
  IdempotencyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -   AttributeName: id
            AttributeType: S
      KeySchema:
        -   AttributeName: id
            KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expiration
        Enabled: true
      BillingMode: PAY_PER_REQUEST

  IdempotencyOldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Test for regular timeout which does not clean up
      CodeUri: src/
      Handler: old.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref IdempotencyTable


  IdempotencyTimeoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Test for clean up after timeout
      CodeUri: src/
      Handler: app.timeout_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref IdempotencyTable

  IdempotencyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Test for no clean up needed
      CodeUri: src/
      Handler: app.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref IdempotencyTable

  PowertoolsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: MyLambdaLayer
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.9
